import { Source_Code_Pro } from 'next/font/google';
import './global.css';

const sourceCodePro = Source_Code_Pro({
  subsets: ['latin', 'cyrillic'],
  variable: '--font-source-code-pro',
});

export const metadata = {
  title: 'Welcome to frontend',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ru" className={sourceCodePro.className}>
      <body>{children}</body>
    </html>
  );
}
